# Generated by Django 4.2.30 on 2026-06-18 18:38

import api.validators
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "doctor_first_name",
                    models.CharField(max_length=500, verbose_name="Имя"),
                ),
                (
                    "doctor_second_name",
                    models.CharField(max_length=500, verbose_name="Фамилия"),
                ),
                (
                    "doctor_third_name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "doctor_date_of_birth",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[api.validators.validate_birth_date],
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "doctor_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctors_photo/",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "doctor_phone_number",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[api.validators.validate_phone_number],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "doctor_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "doctor_workplace",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Место работы",
                    ),
                ),
                (
                    "doctor_experience",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Опыт работы"
                    ),
                ),
                (
                    "doctor_description",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="О себе"
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisIndicators",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_indicators_type",
                    models.CharField(max_length=500, verbose_name="Тип показателя"),
                ),
                (
                    "analysis_indicators_name",
                    models.CharField(
                        max_length=500, verbose_name="Название показателя"
                    ),
                ),
                (
                    "analysis_indicators_slug",
                    models.SlugField(max_length=500, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Показатель анализов",
                "verbose_name_plural": "Показатели анализов",
            },
        ),
        migrations.CreateModel(
            name="ChronicDiseas",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chronic_diseas_name",
                    models.CharField(
                        max_length=1500,
                        unique=True,
                        verbose_name="Название заболевания",
                    ),
                ),
                (
                    "chronic_diseas_slug",
                    models.SlugField(max_length=500, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Хроническое заболевание",
                "verbose_name_plural": "Хронические заболевания",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization_name",
                    models.CharField(
                        max_length=500,
                        unique=True,
                        verbose_name="Название специализации",
                    ),
                ),
                (
                    "specialization_slug",
                    models.SlugField(max_length=500, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Специализация врача",
                "verbose_name_plural": "Специализации врача",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_first_name",
                    models.CharField(max_length=500, verbose_name="Имя"),
                ),
                (
                    "patient_second_name",
                    models.CharField(max_length=500, verbose_name="Фамилия"),
                ),
                (
                    "patient_third_name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "patient_date_of_birth",
                    models.DateField(
                        validators=[api.validators.validate_birth_date],
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "patient_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="patient_photo/",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "patient_phone_number",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[api.validators.validate_phone_number],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "patient_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "patient_password",
                    models.CharField(
                        max_length=250,
                        validators=[api.validators.validate_password],
                        verbose_name="Пароль",
                    ),
                ),
                (
                    "patient_last_update",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последнее обновление данных",
                    ),
                ),
                (
                    "patient_auth_token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Токен авторизации",
                    ),
                ),
                (
                    "patient_invite_code",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        unique=True,
                        verbose_name="Код привязки",
                    ),
                ),
                (
                    "patient_diagnosis",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="api.chronicdiseas",
                        verbose_name="Диагнозы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("Diary", "Дневник"),
                            ("Analysis", "Анализы"),
                            ("Document", "Документы"),
                            ("Device", "Данные с устройства"),
                        ],
                        max_length=100,
                        verbose_name="Тип уведомления",
                    ),
                ),
                ("notification_message", models.TextField(verbose_name="Уведомление")),
                (
                    "notification_is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "notification_created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "notification_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
                (
                    "notification_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-notification_created_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "note_description",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Запись"
                    ),
                ),
                (
                    "note_reason",
                    models.CharField(max_length=100, verbose_name="На основании"),
                ),
                (
                    "note_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Доктор",
                    ),
                ),
                (
                    "note_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Analyzes", "Анализы"),
                            ("Report", "Заключение врача"),
                            ("Results", "Результаты обследований"),
                            ("Other", "Прочее"),
                        ],
                        max_length=100,
                        verbose_name="Тип документа",
                    ),
                ),
                ("document_file", models.FileField(upload_to="documents/")),
                (
                    "document_name",
                    models.CharField(max_length=500, verbose_name="Название документа"),
                ),
                (
                    "document_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки документа"
                    ),
                ),
                (
                    "document_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл пациента",
                "verbose_name_plural": "Файлы пациентов",
            },
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diary_date",
                    models.DateTimeField(verbose_name="Дата отправки данных"),
                ),
                (
                    "diary_health",
                    models.IntegerField(
                        default=1,
                        validators=[api.validators.validate_mark],
                        verbose_name="Самочувствие",
                    ),
                ),
                (
                    "diary_efficiency",
                    models.IntegerField(
                        default=1,
                        validators=[api.validators.validate_mark],
                        verbose_name="Работоспособность",
                    ),
                ),
                (
                    "diary_sleep",
                    models.IntegerField(
                        default=1,
                        validators=[api.validators.validate_mark],
                        verbose_name="Сон",
                    ),
                ),
                (
                    "diary_appetite",
                    models.IntegerField(
                        default=1,
                        validators=[api.validators.validate_mark],
                        verbose_name="Аппетит",
                    ),
                ),
                (
                    "diary_mood",
                    models.IntegerField(
                        default=1,
                        validators=[api.validators.validate_mark],
                        verbose_name="Настроение",
                    ),
                ),
                (
                    "diary_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневник самочувствия пациента",
                "verbose_name_plural": "Дневник самочувствия пациентов",
            },
        ),
        migrations.CreateModel(
            name="DeviceData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "devicedata_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "devicedata_steps",
                    models.IntegerField(
                        default=1,
                        validators=[api.validators.validate_steps],
                        verbose_name="Кол-во шагов",
                    ),
                ),
                (
                    "devicedata_pulse",
                    models.IntegerField(default=1, verbose_name="Пульс"),
                ),
                (
                    "devicedata_temperature",
                    models.FloatField(verbose_name="Температура тела"),
                ),
                (
                    "devicedata_spo2",
                    models.IntegerField(default=1, verbose_name="SpO2"),
                ),
                ("devicedata_sleep_time", models.CharField(verbose_name="Время сна")),
                (
                    "devicedata_sleep_score",
                    models.IntegerField(
                        default=1,
                        validators=[api.validators.validate_mark_device],
                        verbose_name="Оценка сна",
                    ),
                ),
                (
                    "devicedata_stress",
                    models.IntegerField(default=1, verbose_name="Уровень стресса"),
                ),
                (
                    "devicedata_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные с устройства",
                "verbose_name_plural": "Данные с устройства",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_datetime",
                    models.DateTimeField(verbose_name="Дата и время приёма"),
                ),
                (
                    "appointment_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
                (
                    "appointment_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на приём",
                "verbose_name_plural": "Записи на приёмы",
                "ordering": ["appointment_datetime"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisNotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes_value", models.FloatField(verbose_name="Численное значение")),
                (
                    "notes_measure",
                    models.CharField(max_length=100, verbose_name="Ед.изм"),
                ),
                ("notes_date", models.DateTimeField(verbose_name="Дата")),
                (
                    "notes_indicators",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.analysisindicators",
                        verbose_name="Наименование анализа",
                    ),
                ),
                (
                    "notes_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ пользователя",
                "verbose_name_plural": "Анализы пользователя",
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="doctor_specialization",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="api.specialization",
                verbose_name="Специализация",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="DoctorPatientAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_status",
                    models.CharField(
                        choices=[
                            ("Active", "Активный"),
                            ("Archived", "Архивированный"),
                        ],
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "assignment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "assignment_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Доктор",
                    ),
                ),
                (
                    "assignment_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь доктора и пациента",
                "verbose_name_plural": "Связи доктора и пациента",
                "unique_together": {("assignment_doctor", "assignment_patient")},
            },
        ),
    ]
